### ISSUE TITLE
进不去OC，

### ISSUE THREAD

**Issue by 1282129830** [sqlsec/CHUWI-COREBOOK-X-I5-8259U#1]
![00EADD67-C608-492B-9044-9198537FC6C4](https://user-images.githubusercontent.com/57256929/130140423-fd562f6c-42b0-4432-b600-ef8896475516.jpeg)
进不去OC 大佬帮帮忙看看吧.
刚入手就整不会了，可以进PE.

**Comment by sqlsec** [comment]
1.1 版本的 RELEASE 也不可以吗

**Comment by sqlsec** [comment]
我记得B站之前也有一个小伙伴也是这个问题后面 他解决了 可以私聊他看看呢 @Kimhong脱口熊

**Comment by 1282129830** [comment]
两个版本都试了，全部都进不去.

**Comment by zhangan115** [comment]
我的也进不去

**Comment by 1282129830** [comment]
> 我的也进不去

找到解决办法和我说一下呀,太难了

**Comment by zhangan115** [comment]
@1282129830  还在实验。估计是bios 哪里设置的问题。

**Comment by wengkun** [comment]
当你下载了国光大神的EFI后需要把/EFI/BOOT/里的BOOTx64.efi文件替换替换成官方OpenCore的BOOTx64.efi，还有/EFI/OC/里的OpenCore.efi也要替换，应该就可以了，记得先把BIOS设置给改了

**Comment by zhangan115** [comment]
@wengkun 谢了，可以进oc了。

**Comment by 1282129830** [comment]
thank you all
