### ISSUE TITLE
插hdmi显示器后，开机主屏无显示

### ISSUE THREAD

**Issue by icycommond** [sqlsec/CHUWI-COREBOOK-X-I5-8259U#2]
如标题，主屏无显示，观察发现不是灭屏，主屏有显示，但是全黑，外接显示器正常显示。
手动睡眠后，等10s再启动，则大概率正常显示登录界面。
经测试，开启/关闭 HiDPI都有这个现象。
EFI为1.2，低版本没测试过。

**Comment by sqlsec** [comment]
收到 但是这个项目我没法维护了 等其他大佬的完善吧

**Comment by icycommond** [comment]
更新一下，
外接显示器后，2-3小时后容易死机：屏幕卡住不动，键盘/鼠标/触控板都没反应，长按关机后重启出五国，再重启就好了；
不接显示器运行了一天暂时没复现。

另外其他大佬的项目方便指个路吗？  感谢
