### ISSUE TITLE
English translation (recovery too) and new update?

### ISSUE THREAD

**Issue by farisoftfry** [sqlsec/CHUWI-COREBOOK-X-I5-8259U#3]
Hello, first of all thanks for your wonderful work!
Do you plan to translate your work (google translate sometime it is not enough) and provide more update that solve existing problems?
Thanks
Regards

**Comment by sqlsec** [comment]
I'll think about it. I'm a bit busy lately.

**Comment by farisoftfry** [comment]
ok thanks for your great work! I'm keeping my finger crossed, hoping and waiting for your update!  thanks!

**Comment by sqlsec** [comment]
目前这个笔记本的项目已经有 @weachy & @王刚 大佬维护了，他们的项目地址为：
[https://github.com/weachy/CoreBookX-14-Hackintosh](https://github.com/weachy/CoreBookX-14-Hackintosh) 
感兴趣的朋友可以关注一下

At present, this notebook project has been maintained by @weachy & @王刚大佬, and their project address is: [https://github.com/weachy/CoreBookX-14-Hackintosh](https://github.com/weachy/CoreBookX-14-Hackintosh)
Interested friends can follow
