### ISSUE TITLE
Strange Situation

### ISSUE THREAD

**Issue by xLidoni** [sqlsec/CHUWI-COREBOOK-X-I5-8259U#4]
Hello!

I am in a strange situation, I cannot get the WiFi to work.

kext loads, but it doesn't work.
Checking with Hackintool my corebook has

realtek 8821CE( not compatible)

but it should have an intel AC7265

I am wrong?

**Comment by sqlsec** [comment]
It is recommended to contact the official return and exchange, the follow-up corebook core x wireless network card used there is mixed, I am also very distressed about this
